import React from 'react';
import { Alert } from '@mui/material';

const Disclaimer = () => {
    return (
        <Alert severity="info">
            This analysis is generated by AI and should be used as a guide, not as definitive fact-checking.
            Always verify information from multiple reliable sources.
        </Alert>
    );
};

export default Disclaimer;
